/**
 * Mock API Service
 * Simulates backend API calls for evidence analysis
 */

import { Message } from '../constants/Types';
import { AI_RESPONSES } from '../constants/MockData';
import { delay, getRandomItem } from '../utils/helpers';

/**
 * Analyze image with AI
 * @param imageUri - URI of image to analyze
 * @param prompt - Optional analysis prompt
 * @returns Promise resolving to AI analysis text
 */
export const analyzeImage = async (
  imageUri: string,
  prompt?: string
): Promise<string> => {
  // Simulate API delay
  await delay(2000);

  // Determine response type based on prompt
  let responses = AI_RESPONSES.default;
  
  if (prompt) {
    const lowerPrompt = prompt.toLowerCase();
    if (lowerPrompt.includes('identify') || lowerPrompt.includes('what')) {
      responses = AI_RESPONSES.identify;
    } else if (lowerPrompt.includes('analyze') || lowerPrompt.includes('how')) {
      responses = AI_RESPONSES.analyze;
    } else if (lowerPrompt.includes('scene') || lowerPrompt.includes('where')) {
      responses = AI_RESPONSES.scene;
    }
  }

  // Return random response from appropriate category
  return getRandomItem(responses);
};

/**
 * Generate forensic report from chat history
 * @param chatHistory - Array of chat messages
 * @param evidenceTags - Array of evidence tags
 * @returns Promise resolving to formatted report
 */
export const generateReport = async (
  chatHistory: Message[],
  evidenceTags: string[]
): Promise<string> => {
  // Simulate API delay for report generation
  await delay(3000);

  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  // Extract key information from chat
  const userMessages = chatHistory.filter(m => m.role === 'user');
  const aiMessages = chatHistory.filter(m => m.role === 'assistant');

  // Build report content
  const report = `
FORENSIC ANALYSIS REPORT
Generated: ${currentDate}

EXECUTIVE SUMMARY
This report documents the forensic analysis conducted on submitted evidence materials. The analysis utilized advanced AI-assisted examination techniques to identify and document potential evidentiary value.

EVIDENCE DESCRIPTION
Total evidence items analyzed: ${chatHistory.filter(m => m.imageUri).length}
Evidence categories identified: ${evidenceTags.join(', ')}

ANALYSIS METHODOLOGY
The evidence was examined using AI-powered image analysis and forensic pattern recognition. Each piece of evidence was systematically documented and analyzed for potential investigative value.

KEY FINDINGS
${aiMessages.slice(0, 3).map((msg, idx) => `
${idx + 1}. ${msg.content.substring(0, 200)}${msg.content.length > 200 ? '...' : ''}
`).join('')}

RECOMMENDATIONS
Based on the analysis conducted, the following actions are recommended:

1. High-Resolution Documentation
   - Capture detailed photographs of all identified evidence
   - Maintain proper scale and lighting conditions
   - Document from multiple angles

2. Laboratory Analysis
   - Submit biological materials for DNA analysis
   - Conduct comparative analysis of tool marks and impressions
   - Perform chemical analysis of trace evidence

3. Database Comparison
   - Submit fingerprints to AFIS
   - Compare tool marks with known database
   - Check ballistic evidence against NIBIN

4. Chain of Custody
   - Ensure proper evidence packaging and sealing
   - Maintain detailed documentation of all transfers
   - Preserve evidence integrity throughout process

CONCLUSION
The forensic examination revealed several pieces of potentially significant evidence. Further laboratory analysis and comparison testing is recommended to maximize the investigative value of the collected materials.

The evidence should be processed according to established forensic protocols and submitted to appropriate specialized laboratories for confirmation and detailed analysis.

ANALYST NOTES
This preliminary analysis provides initial assessment of evidentiary materials. Final determinations should be made only after comprehensive laboratory testing and expert examination.

Report generated by Forensic AI Analysis System
For official use only - Maintain confidentiality
  `.trim();

  return report;
};

/**
 * Get AI suggestion based on context
 * @param context - Current context (e.g., 'initial', 'follow-up')
 * @returns Promise resolving to suggestion text
 */
export const getAISuggestion = async (context: string): Promise<string[]> => {
  await delay(500);

  const suggestions: { [key: string]: string[] } = {
    initial: [
      'Identify objects in this image',
      'Analyze the scene composition',
      'Find potential evidence',
    ],
    followUp: [
      'What else can you see?',
      'Analyze in more detail',
      'Generate forensic report',
    ],
    weapon: [
      'Describe the weapon type',
      'Identify distinctive markings',
      'Assess potential evidence value',
    ],
    biological: [
      'Describe biological evidence',
      'Recommend collection method',
      'Assess preservation requirements',
    ],
  };

  return suggestions[context] || suggestions.initial;
};

/**
 * Extract evidence tags from AI response
 * @param aiResponse - AI response text
 * @returns Array of evidence tags
 */
export const extractEvidenceTags = async (aiResponse: string): Promise<string[]> => {
  await delay(300);

  const tags: string[] = [];
  const lowerResponse = aiResponse.toLowerCase();

  // Map of keywords to tags
  const tagKeywords: { [key: string]: string[] } = {
    weapon: ['weapon', 'knife', 'gun', 'firearm', 'blade'],
    blood: ['blood', 'bloodstain', 'spatter', 'biological'],
    fingerprint: ['fingerprint', 'print', 'latent', 'ridge'],
    vehicle: ['vehicle', 'car', 'tire', 'track'],
    document: ['document', 'paper', 'writing', 'note'],
    trace: ['trace', 'fiber', 'hair', 'particle'],
    biological: ['dna', 'saliva', 'biological', 'tissue'],
    digital: ['phone', 'digital', 'device', 'computer'],
    'tool mark': ['tool', 'pry', 'mark', 'impression'],
    fibers: ['fiber', 'fabric', 'cloth', 'textile'],
  };

  // Check for each tag keyword in response
  Object.entries(tagKeywords).forEach(([tag, keywords]) => {
    if (keywords.some(keyword => lowerResponse.includes(keyword))) {
      if (!tags.includes(tag)) {
        tags.push(tag);
      }
    }
  });

  // Return at least one tag
  return tags.length > 0 ? tags : ['trace'];
};

/**
 * Mock chat with AI assistant
 * @param message - User message
 * @param imageUri - Optional image URI
 * @returns Promise resolving to AI response message
 */
export const chatWithAI = async (
  message: string,
  chatHistory: Message[],
  imageUri?: string
): Promise<Message> => {
  // Blend the latest conversation context into the prompt to keep responses relevant
  const recentContext = chatHistory
    .slice(-3)
    .map(entry => entry.content)
    .join(' ');

  const prompt = [message, recentContext].filter(Boolean).join(' ').trim();

  const response = await analyzeImage(imageUri || '', prompt || message);

  // Create AI message
  const aiMessage: Message = {
    id: `msg-${Date.now()}`,
    role: 'assistant',
    content: response,
    timestamp: new Date(),
  };

  return aiMessage;
};
